language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  - chrome: stable
before_install: 
  - npm i -g codecov
install:
  - yarn
script:
  - npm run lint
  - npm run test
  - codecov
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - export CODECOV_TOKEN="e40866c2-cf7f-4630-9dee-d147921fcbe3"
  - bash <(curl -s https://codecov.io/bash) -s coverage/