language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
addons:
  - chrome: stable
before_install: 
  - npm i -g codecov
install:
  - yarn
  - yarn bootstrap
script:
  - yarn lint
  - yarn test
  - codecov
cache:
  yarn: true
  directories:
    - node_modules
after_success:
  - export CODECOV_TOKEN="89b2f8a0-3572-4660-afa9-e899c57e21d1"
  - bash <(curl -s https://codecov.io/bash) -s packages/**/coverage/